"""Inicial: crear tablas

Revision ID: 49404cfd8ef5
Revises: 
Create Date: 2025-09-07 23:34:42.605383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49404cfd8ef5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CUENTA',
    sa.Column('mail', sa.String(length=120), nullable=False),
    sa.Column('nombre_cuenta', sa.String(length=128), nullable=False),
    sa.Column('contrasenia', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('mail')
    )
    op.create_table('GENERO',
    sa.Column('id_genero', sa.Integer(), nullable=False),
    sa.Column('nombre_genero', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id_genero')
    )
    op.create_table('GRUPO',
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('nombre_grupo', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id_grupo')
    )
    op.create_table('PAIS',
    sa.Column('id_pais', sa.Integer(), nullable=False),
    sa.Column('nombre_pais', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id_pais'),
    sa.UniqueConstraint('nombre_pais')
    )
    op.create_table('PELICULA',
    sa.Column('id_pelicula', sa.Integer(), nullable=False),
    sa.Column('trama', sa.String(length=1024), nullable=False),
    sa.Column('anio_lanzamiento', sa.DateTime(), nullable=False),
    sa.Column('titulo', sa.String(length=128), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('clasificacion_edad', sa.String(length=128), nullable=False),
    sa.Column('url_poster', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_pelicula')
    )
    op.create_table('PLATAFORMA',
    sa.Column('id_plataforma', sa.Integer(), nullable=False),
    sa.Column('nombre_plataforma', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id_plataforma'),
    sa.UniqueConstraint('nombre_plataforma')
    )
    op.create_table('ADMIN',
    sa.Column('mail', sa.String(length=120), nullable=False),
    sa.Column('mail_creador', sa.String(length=120), nullable=True),
    sa.Column('eliminado_por_mail', sa.String(length=120), nullable=True),
    sa.Column('esta_eliminado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['eliminado_por_mail'], ['ADMIN.mail'], ),
    sa.ForeignKeyConstraint(['mail'], ['CUENTA.mail'], ),
    sa.ForeignKeyConstraint(['mail_creador'], ['ADMIN.mail'], ),
    sa.PrimaryKeyConstraint('mail')
    )
    op.create_table('GENERO_PELICULA',
    sa.Column('id_pelicula', sa.Integer(), nullable=False),
    sa.Column('id_genero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_genero'], ['GENERO.id_genero'], ),
    sa.ForeignKeyConstraint(['id_pelicula'], ['PELICULA.id_pelicula'], ),
    sa.PrimaryKeyConstraint('id_pelicula', 'id_genero')
    )
    op.create_table('PELICULA_PLATAFORMA',
    sa.Column('id_plataforma', sa.Integer(), nullable=False),
    sa.Column('id_pelicula', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pelicula'], ['PELICULA.id_pelicula'], ),
    sa.ForeignKeyConstraint(['id_plataforma'], ['PLATAFORMA.id_plataforma'], ),
    sa.PrimaryKeyConstraint('id_plataforma', 'id_pelicula')
    )
    op.create_table('PLATAFORMA_PAIS',
    sa.Column('id_plataforma', sa.Integer(), nullable=False),
    sa.Column('id_pais', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pais'], ['PAIS.id_pais'], ),
    sa.ForeignKeyConstraint(['id_plataforma'], ['PLATAFORMA.id_plataforma'], ),
    sa.PrimaryKeyConstraint('id_plataforma', 'id_pais')
    )
    op.create_table('USUARIO',
    sa.Column('mail', sa.String(length=128), nullable=False),
    sa.Column('id_pais', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pais'], ['PAIS.id_pais'], ),
    sa.ForeignKeyConstraint(['mail'], ['CUENTA.mail'], ),
    sa.PrimaryKeyConstraint('mail')
    )
    op.create_table('GENERO_FAVORITO',
    sa.Column('id_genero', sa.Integer(), nullable=False),
    sa.Column('mail_usuario', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['id_genero'], ['GENERO.id_genero'], ),
    sa.ForeignKeyConstraint(['mail_usuario'], ['USUARIO.mail'], ),
    sa.PrimaryKeyConstraint('id_genero', 'mail_usuario')
    )
    op.create_table('PELICULAS_FAVORITAS',
    sa.Column('mail_usuario', sa.String(length=128), nullable=False),
    sa.Column('id_pelicula', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pelicula'], ['PELICULA.id_pelicula'], ),
    sa.ForeignKeyConstraint(['mail_usuario'], ['USUARIO.mail'], ),
    sa.PrimaryKeyConstraint('mail_usuario', 'id_pelicula')
    )
    op.create_table('USUARIO_GRUPO',
    sa.Column('mail_usuario', sa.String(length=128), nullable=False),
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_grupo'], ['GRUPO.id_grupo'], ),
    sa.ForeignKeyConstraint(['mail_usuario'], ['USUARIO.mail'], ),
    sa.PrimaryKeyConstraint('mail_usuario', 'id_grupo')
    )
    op.create_table('USUARIO_PLATAFORMA',
    sa.Column('mail_usuario', sa.String(length=128), nullable=False),
    sa.Column('id_plataforma', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_plataforma'], ['PLATAFORMA.id_plataforma'], ),
    sa.ForeignKeyConstraint(['mail_usuario'], ['USUARIO.mail'], ),
    sa.PrimaryKeyConstraint('mail_usuario', 'id_plataforma')
    )
    op.create_table('USUARIO_VIO_PELI',
    sa.Column('mail_usuario', sa.String(length=128), nullable=False),
    sa.Column('id_pelicula', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pelicula'], ['PELICULA.id_pelicula'], ),
    sa.ForeignKeyConstraint(['mail_usuario'], ['USUARIO.mail'], ),
    sa.PrimaryKeyConstraint('mail_usuario', 'id_pelicula')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('USUARIO_VIO_PELI')
    op.drop_table('USUARIO_PLATAFORMA')
    op.drop_table('USUARIO_GRUPO')
    op.drop_table('PELICULAS_FAVORITAS')
    op.drop_table('GENERO_FAVORITO')
    op.drop_table('USUARIO')
    op.drop_table('PLATAFORMA_PAIS')
    op.drop_table('PELICULA_PLATAFORMA')
    op.drop_table('GENERO_PELICULA')
    op.drop_table('ADMIN')
    op.drop_table('PLATAFORMA')
    op.drop_table('PELICULA')
    op.drop_table('PAIS')
    op.drop_table('GRUPO')
    op.drop_table('GENERO')
    op.drop_table('CUENTA')
    # ### end Alembic commands ###
